# Taken from github: GodotNuts/GodotServer-Docker
#
version: '3'

services:
  godot:
    build: .
    ports:
      - "12345:12345"
      - "12345:12345/udp"
    tty: true
    container_name: godot-repl-server
